### ISSUE TITLE
background appears slightly when border is white

### ISSUE THREAD

**Issue by prabuinet** [soundar24/roundSlider#1]
if the .rs-border is #fff, it appears like in the image attached.

![image](https://cloud.githubusercontent.com/assets/36747/8845657/9c36d5ec-313e-11e5-9473-a11310b1390a.png)

**Comment by soundar24** [comment]
Hello prabuinet,

The control uses the CSS3 styles, so while apply the transformation styles the element edges are looks like jagged. But this also occurs only when set the border and path color as white, in remaining cases there is no problem with appearances. So there is no need to fix this in source, alternatively we can solve this in application level by overwritting the CSS styles.

Check the solution here: http://jsfiddle.net/soundar24/fe7j3ohv/4/

so now the output looks like:
![image](https://cloud.githubusercontent.com/assets/8916666/8873324/00d361de-3223-11e5-8cc6-e2ed0fcd8ca4.png)

**Comment by prabuinet** [comment]
soundar, thanks

**Comment by soundar24** [comment]
@prabuinet @korn3l @const-int

This might be after a very very long back, but a new and useful update.

roundSlider was released with **SVG mode** support, so now all the layout and animation related bugs are resolved.

### Demo: https://jsfiddle.net/soundar24/r5jcb1q4/4/
