### ISSUE TITLE
prevent roundslider to jump from 100 to 0

### ISSUE THREAD

**Issue by janphilippbehrens** [soundar24/roundSlider#106]
Is there any way to prevent that roundslider jumps to 0 again after the user has reached the 100 (and drags a little bit to far) in a full circle ? In other words, the slider should stop at 100 und the user must go counterclockwise to reach the 0 again?

**Comment by soundar24** [comment]
@janphilippbehrens are you asking about the same behaviour mentioned here https://github.com/soundar24/roundSlider/issues/105

Check the below demo and let me know your comments:
### https://jsfiddle.net/soundar24/1n87Lh6e/

**Comment by janphilippbehrens** [comment]
Yes, indeed. This is what I was looking for. For some reason I missed #105. Thank you for your quick help.
