### ISSUE TITLE
Minified file does not end with ;

### ISSUE THREAD

**Issue by migglu** [soundar24/roundSlider#11]
This causes problems when concatenating multiple minified javascript files (as to serve them with one request instead of many) and was particularly annoying to find... This comment helped me a lot: http://stackoverflow.com/a/25412298

**Comment by soundar24** [comment]
I will consider this and update the source in the next version.

**Comment by soundar24** [comment]
Thanks for your contribution @migglu ..

The reported problem was solved in version 1.2, Please check the below file:
http://cdn.jsdelivr.net/jquery.roundslider/1.2/roundslider.min.js
