### ISSUE TITLE
max drag limit for handle of min-range slider

### ISSUE THREAD

**Issue by janphilippbehrens** [soundar24/roundSlider#110]
Hi,
I am looking for a way to set a max drag value for the handle of the min-range slider. 
The roundSlider should be a full circle all the time and its maximal value should be 100! But I want the handle not to go over a specific value. Let’s say that the user can only drag the handle up to 50 in one case and up to 66 in another. 
Please see my illustration.

![roundSlider_dragmax](https://user-images.githubusercontent.com/38940441/104847135-99211c00-58de-11eb-999d-8e56ec4d2d2a.jpg)

It would be nice to show the user where the max drag value is located.

**Comment by soundar24** [comment]
@janphilippbehrens yes, you can achieve the same requirement with roundSlider.. by using the `beforeValueChange` event you manage the handle drag behaviour based on any conditional cases. And for showing the visual appearance of the max drag point I have added a simple sample level customization.

Check the below demo and let me know your comments:
### https://jsfiddle.net/soundar24/x3umroj6/

**Comment by janphilippbehrens** [comment]
This is exactly what I was looking for :)
Thank you very much for your great support!
