### ISSUE TITLE
Animate Slider

### ISSUE THREAD

**Issue by NinjaBuoy** [soundar24/roundSlider#111]
Is there a way to animate slider. By that, I mean, say, I want the slider to stop at every 10th position (10, 20, 30......, 100) position. Nowhere in between.

**Comment by NinjaBuoy** [comment]
Sorry, I found this in one of the threads https://jsfiddle.net/cvdtLx0y/. However, I still need this in Vue.js version

**Comment by soundar24** [comment]
@NinjaBuoy are you expect the below:

### http://vue.roundsliderui.com/

**Demos:**
https://codesandbox.io/s/vue-round-slider-demo-oz8el
https://codesandbox.io/s/label-number-around-circle-91tgg
