### ISSUE TITLE
Detect if the slider is being dragged

### ISSUE THREAD

**Issue by allan-simon** [soundar24/roundSlider#112]
my use case:

I would, when inactive, that every  5 seconds, the slider  change a bit its value to demonstrate to the user the value can change
I can easily do that by adding a timer and programmatically changing the value

however I don't want it to happen when the user is actually moving manually the slider 

is there a way to detect this ?

**Comment by soundar24** [comment]
@allan-simon I am not sure where this use case will be used.. but you can easily detect whether the slider is dragged or not from the [**`start`**](https://roundsliderui.com/document.html#start) and [**`stop`**](https://roundsliderui.com/document.html#stop) events.. these events will be triggered when the user starts to drag the handle and releases.. so at that time you can enable a flag to keep this status.. based on that flag status you can change the slider value in a periodical interval..

Check the below demo and let me know your comments:
### https://jsfiddle.net/soundar24/ct31q7v5/

**Comment by soundar24** [comment]
@allan-simon Feel free to re-open this if you are facing any issues still.
