### ISSUE TITLE
.roundSlider is not a function

### ISSUE THREAD

**Issue by Tahir-Musharraf** [soundar24/roundSlider#113]
.roundSlider is a function that works in the local environment but shows an error on the live server (webflow). 
I'm setting the value of the slider using setValue attributes. 

$("#slider_up").roundSlider("setValue", value*(2500));

**Comment by soundar24** [comment]
@Tahir-Musharraf  Are you getting this error?
`Uncaught TypeError: $(...).roundSlider is not a function`
Then it seems in your server the roundSlider source was missed.. just confirm that your live server refers the `roundslider.js` file somewhere. That is the most possible case.

Otherwise you can share me your demo site url or something where I can reproduce the bug, so that it's much better to suggest you.

**Comment by Tahir-Musharraf** [comment]
Hi, here is my demo on webflow: https://www.mimosainvestments.com/calculator

The drag working perfectly but keyup function causes problems.

**Comment by Tahir-Musharraf** [comment]
Problem solved: Thanks @soundar24 , Actually I was using Cloudflare CDN version, Now I just change the link with original CDN:
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>                                  
<link href="https://cdn.jsdelivr.net/npm/round-slider@1.6.1/dist/roundslider.min.css" rel="stylesheet" />                  
<script src="https://cdn.jsdelivr.net/npm/round-slider@1.6.1/dist/roundslider.min.js"></script>

**Comment by Tahir-Musharraf** [comment]
Still, the same issue but this time slider is no longer visible. @soundar24 can you please check the error via f12.

**Comment by soundar24** [comment]
@Tahir-Musharraf in your mentioned link the roundSlider was working.. I can see that.. can you let me what issue you are facing.. or where can I see the issue in your demo page

**Comment by Tahir-Musharraf** [comment]
Thanks, @soundar24, Actually the problem is with webflow, web flow is calling two times jquery, Once I called it and second-time web flow, that caused an error. As web flow renders jquery script at the last of the HTML but my code must be after the jquery so to fix it I have to import the script as an external source with defer attribute. Thanks for your quick reply.
