### ISSUE TITLE
Value doesn't get refreshed during drag

### ISSUE THREAD

**Issue by mirk-00** [soundar24/roundSlider#115]
Maybe it's just me, but it looks like the value doesn't get refreshed while dragging but only after the user stopped moving the slider. It would be useful to be able to access the value in real time, but again it can just be me accessing in the wrong way.
I'm doing it with mySlider.childNodes[1].value where mySlider is obtained with querySelector(). # #

**Comment by soundar24** [comment]
I am not sure how you are accessed the value.. suppose if you are using the [`change`](https://roundsliderui.com/document.html#change) event then, converting it to the. [`update`](https://roundsliderui.com/document.html#update) event ll resolve your problem. You can check the below demo:
https://jsfiddle.net/soundar24/hd0xj3kn/2/

If still you are facing any issue then let me know with some more details.. thanks

**Comment by soundar24** [comment]
@mirk-00 Feel free to re-open this if you are facing any issues still.
