### ISSUE TITLE
Is it possible to have a clock range picker?

### ISSUE THREAD

**Issue by zhangj1an** [soundar24/roundSlider#116]
I want to select a time interval on a round clock, say from 22:00 to 02:00. This passes the zero hour, which is not supported. The two buttons are on the same clock.

Is there any workaround to this?

Much thanks in advance!

**Comment by soundar24** [comment]
@zhangj1an are you expect something like this?
https://jsfiddle.net/soundar24/t4caLfkx/

Check this demo and let me know your comments.. thanks...

**Comment by zhangj1an** [comment]
Hi,
thanks a lot for this!
I wanted a starting time thumb and a ending time thumb, with all 12 hours available (full circle).

But I already found a workaround by using two seperate linear sliders.
Much thanks! I like this repo a lot.
