### ISSUE TITLE
counter clock-wise ?

### ISSUE THREAD

**Issue by elkizana** [soundar24/roundSlider#124]
First thank you @soundar24 for this nice work you offered.
I want to have a counter clock-wise  circle slider, how do I achieve it ? 
I  used transform/rotate but it  didn't  seem  clean to me

**Comment by soundar24** [comment]
Hello @elkizana , Thanks. Are you expect like below:
https://jsfiddle.net/soundar24/wr3x72yt/

If so, just swap the `min` and `max` values and then update the `startValue` as max value.

**Comment by elkizana** [comment]
like this : 
![Screenshot from 2022-12-20 19-32-22](https://user-images.githubusercontent.com/53874333/208740807-08637c8e-93bf-45c9-8c38-f190ccb81164.png)

**Comment by soundar24** [comment]
Check the below updated demo:
https://jsfiddle.net/soundar24/wr3x72yt/1/

Also you can check the all available options to customize the roundSlider:
https://roundsliderui.com/document.html#options

**Comment by elkizana** [comment]
thanks  a lot !

**Comment by elkizana** [comment]
please how can I have the same result for a full circle ?

**Comment by soundar24** [comment]
@elkizana you have the [`circleShape`](https://roundsliderui.com/document.html#circleShape) property by using that you can achieve all the shapes, and you have the [`startAngle`](https://roundsliderui.com/document.html#startAngle) which helps to customize the start position.

**Comment by elkizana** [comment]
> @elkizana you have the [`circleShape`](https://roundsliderui.com/document.html#circleShape) property by using that you can achieve all the shapes, and you have the [`startAngle`](https://roundsliderui.com/document.html#startAngle) which helps to customize the start position.

yes but but how to make  it counter clockwise ?

**Comment by soundar24** [comment]
I can't get your requirement, the initial demo I shared also a full circle only. Maybe check this as well, if not share me more info.
https://jsfiddle.net/soundar24/wr3x72yt/2/
