### ISSUE TITLE
Value update at slidestop / handle release

### ISSUE THREAD

**Issue by wvhn** [soundar24/roundSlider#125]
Hi @soundar24 

for many applications like e.g. tuning the speaker volume of a sound device it is good to have the slider sending value updates in live mode with immediate feedback - which the roundslider does well. For other applications where the controlled device reacts with delay, i need a slider updating only once at the end of drag / release of the handle or after a click on the slider track. The latter works well, too on the roundslider.

Is there a way to block live value updates until manual interaction with the slider has ended? 

Thanks and best regards
Wolfram

**Comment by soundar24** [comment]
@wvhn I am little confused with your requirement, seems you are expecting the "[change](https://roundsliderui.com/document.html#change)" event which works in the simiar way that you are describing. Check the **below demo** to get know the change event behaviour:
https://jsfiddle.net/soundar24/tf2bjwu6/

And also you have a lot of events, check the below document.
https://roundsliderui.com/document.html#valueChange

Still your requirement is not satisfied then please let me know the details.

**Comment by wvhn** [comment]
Hi @soundar24 ,

I had been reading the documentation before but - to be honest - not completely understood the differences between update and change event. 
Thanks for the fiddle. It seems the change event fulfills fully what I need.

I‘ll give it a try and close the issue if the test is successful.

**Comment by wvhn** [comment]
OK. The change request does in deed fulfill the requirement. This is the way I have implemented the live/silent option:
```
		$(element).roundSlider({
			...
			min: this.options.scale_min,
			max: this.options.scale_max,
			step: this.options.step,
			value: user_value,
			svgMode: true,

			update: function (args) {
				if (liveOption == 1)
					io.write(user_value_item, args.value);
			},
			
			change: function (args) {
				if (liveOption == 0)
					io.write(user_value_item, args.value);
```
Maybe the docu could be a bit more precise on the different events.
drag: fires with every value change **during** drag
update: fires like drag and with click on the slider track
change: fires **after** drag if handle is released an with click on the slider track.

Thanks again!
