### ISSUE TITLE
Touch Bug in MS Edge

### ISSUE THREAD

**Issue by jaysn** [soundar24/roundSlider#16]
roundslider on a touchscreen windows 10 device using microsoft edge doenst allow to drag the handle. maybe theres some problem with the touch events handled by edge since its more or less working in ie11 using the same touchscreen device.

**Comment by soundar24** [comment]
Issue resolved in the latest version 1.3.2, check the below demo in IE edge:
http://jsfiddle.net/soundar24/s5gpugjn/
