### ISSUE TITLE
Question: using getValue

### ISSUE THREAD

**Issue by lawrence-c** [soundar24/roundSlider#2]
Hi,

I'm a bit unsure of how to call getValue and was wondering if you could provide an example?

I've tried something similar to what's below, and a few other variations: 

```
var testvalue = $( "#slider" ).getValue();
console.log ( testvalue );
```

Thanks!

**Comment by soundar24** [comment]
Hi,

The problem is due to, you are using the wrong syntax.

Here is the proper syntax to use the **getValue** function:

```
var obj = $("#slider").data("roundSlider");
var testvalue = obj.getValue();
alert(testvalue);
```

Alternatively you can also use like below:

```
var testvalue = $("#slider").roundSlider("getValue");
alert(testvalue);
```

For more details please check: http://roundsliderui.com/document.html#how-to-use-options

Thanks,
Soundar

**Comment by lawrence-c** [comment]
Thanks for the information!
