### ISSUE TITLE
tooltipFormat not working

### ISSUE THREAD

**Issue by jzarca01** [soundar24/roundSlider#24]
I tried using the example provided to add "€" to the tooltip but it doesnt work

**Comment by soundar24** [comment]
I have created the below demo for your requirement:
http://jsfiddle.net/soundar24/deLqk8sr/

Here it was working fine, check this demo and let me know if still you faced any issue.

**Comment by soundar24** [comment]
As per the previous comment this is not a issue.. So I have closed this, If still facing any issue please update me.. Thanks..
