### ISSUE TITLE
Dynamically apply style to rs-control bar background.

### ISSUE THREAD

**Issue by yashilanka** [soundar24/roundSlider#33]
Hi can you show some example about how to style rs-control bar background color. i tried this but it dosen't style full circle, only half of the circle will style, i use same code to add style to the rs-control bg, please follow bellow thread. #31, and appreciate if you can reproduce this simple example.

**Comment by soundar24** [comment]
Here I just updated a simple demo to dynamically update the bg color and range color. Just check the below demo:
http://jsfiddle.net/soundar24/LpuLe9tr/545/

If you want to style the slider initially, then you can use the playground sample which is used to style the control in live:
http://roundsliderui.com/playground.html

Simply, to apply the color dynamucally through jquery you can use like below;
`obj.control.find(".rs-bg-color").css("background", _color);`

**Comment by soundar24** [comment]
Closed this issue now, please let me know if you have any further queries regarding this.
