### ISSUE TITLE
roundSlider not round on android 4.2.2

### ISSUE THREAD

**Issue by akinorikul** [soundar24/roundSlider#34]
Hi, 
I'm using roundSlider in a cordova project and for android 4.2.2, the round layout is not round.
Unfortunately this version of android is using android browser so I have no clue what css isn't working.
Here's a screenshot of my roundSlider:
![capture d ecran 2016-07-01 a 01 07 52](https://cloud.githubusercontent.com/assets/6918264/16507256/d5cf40fc-3f28-11e6-8e62-40822033161a.png)
![capture d ecran 2016-07-01 a 01 13 32](https://cloud.githubusercontent.com/assets/6918264/16507281/12f4bb1a-3f29-11e6-8610-cca0db45e596.png)

**Comment by soundar24** [comment]
Issue resolved with v1.3.2
