### ISSUE TITLE
Como Sacar el valor del Rango / convertirlo a variable.

### ISSUE THREAD

**Issue by judasniper** [soundar24/roundSlider#37]
Estoy usando el min-range sin ningun problema.

Pero necesito obtener el valor del rango para poder hacer una operacion o formula.

ejemplo: voy a usar el numero del rango como unidad de medida de peso.
10=10kg
para luego hacer lo siguiente.

peso \* dosis-maxima / frecuencia.
(10 \* 50) / 3.

como puedo sacar ese valor ya sea auna variable o a algun input type=text para yo poder usar ese valor segun mi necesidad.

**Comment by soundar24** [comment]
I can't get your requirement exactly.. As you stated i think you may need to get the slider value dynamically, you can get the value property the method or public method. So based on that value you can perform any operation.

Please check the below demo:
http://jsfiddle.net/soundar24/LpuLe9tr/556/

If this is not your requirement then let me know the details.

**Comment by judasniper** [comment]
### html

div id="slider" value="get value (way 2)" onclick="getValue2()" ></div>
<br>
span id='Peso' >Peso:</span>
<br>
span id='miligramos' >Dosis:</span>
<br>
span id='mililitros' >Dosis:</span>

<hr>

### JS

$("#slider").roundSlider({
  sliderType: "min-range",
  value: 45
});
window.getValue2 = function () {
    var obj2 =  $("#slider").data("roundSlider");
  var value1 = obj2.option("value");
  var miligramos= Math.round(value1 \* 50 / 3);
  var mililitros= (miligramos) \* 5/ 250; 
   document.getElementById('Peso').innerHTML="Peso:"+value1+" kg";
   document.getElementById('miligramos').innerHTML="Miligramos:"+miligramos+"ml";
     document.getElementById('mililitros').innerHTML="Mililitros:"+mililitros+"ml";
}

Lo logre con tu ayuda. Pero necesito algo mas.

Estoy oteniendo el resultado hasta que suelto el Click("mouseUp")
pero me gustaria que se actualize inmediatemente con el change.

me explico que al girar el slider asi como cambia el valor del centro tambien cambien los resultados de mis calculos

**Comment by soundar24** [comment]
I have updated the demo based on your requirement. Please check the below demo, i hope this is what you need:

http://jsfiddle.net/soundar24/LpuLe9tr/562/

**Comment by judasniper** [comment]
You Are de Best..... Tanks.

Very Taks.

**Comment by soundar24** [comment]
You are welcome ... :) 

I am closing this now...
