### ISSUE TITLE
Using roundSlider as a clock-picker

### ISSUE THREAD

**Issue by NicTorgersen** [soundar24/roundSlider#43]
Hi,

just want to say that this is a great plugin!

I was thinking of the possibilities of using this as a time-picker and style it sort of like a clock. There are no other circular range-sliders that even try to incorporate this idea, however this one seems to be extensible enough to do this quickly and easily.

Do you have any input in regards to this, or have you done it before?

**Comment by soundar24** [comment]
Actually i already thought about this, and i hope you need the time picker similar to the Android timer (you can see the below image).

To achieve this, still some functionalities needed to be include in round slider. Future i planned to enhance the plugin similar to this. If you have any immediate requirement of this then please let me know the details. Thanks :)

![sshot-1](https://cloud.githubusercontent.com/assets/8916666/18608099/77cd67be-7cfd-11e6-88b3-97033ae6262f.png)

**Comment by NicTorgersen** [comment]
I no longer work with the project I used this for, so I'll close this issue.
