### ISSUE TITLE
Get ID from roundSlider that was changed

### ISSUE THREAD

**Issue by shdsmth** [soundar24/roundSlider#49]
Hi there,

We have multiple roundSliders on one page. There is a "change" event available, but how can the ID of the roundSlider that was changed from the event arguments provided by this event?

Thanks in advance.

**Comment by soundar24** [comment]
Currently i didn't provided the id in the event arguments, but inside the event handler "**this**" points the corresponding slider instance. So from that instance you can get all things about the current slider.

**`this.control`** returns the current slider element, so
**`this.control.attr("id")`** returns the id

Check the below demo and let me know if any concerns still:
http://jsfiddle.net/soundar24/LpuLe9tr/694/

**Comment by soundar24** [comment]
Now passed the element id in the event arguments (in version 1.3.2):
http://jsfiddle.net/soundar24/vej1re0y/
