### ISSUE TITLE
Add npm packaging

### ISSUE THREAD

**Issue by floviolleau** [soundar24/roundSlider#51]
Hi,

Could you please add npm packaging of your project?

Kind regards

**Comment by floviolleau** [comment]
Finally, I just did it here:
https://www.npmjs.com/package/npm-round-slider
https://github.com/floviolleau/npm-round-slider

Best regards

**Comment by soundar24** [comment]
Great work, I have updated the roundSlider package in both npm and bower. Check the below comments:

> npm install round-slider
> bower install round-slider

Thanks :)

**Comment by floviolleau** [comment]
Okey super !

I looked on other git repositories and very often, they organize like I did in my repository. A dist folder with minified and normal js / css files and no src folder on simple repositories.

**Comment by soundar24** [comment]
Actually the purpose was identical, to maintain the source and distributable files in a structure. Until the source was simple it doesn't make any problem, but when we split up the source in various modules at that time it makes complex for minify and concat.

Just see here: http://stackoverflow.com/questions/22842691/what-is-the-meaning-of-the-dist-directory-in-open-source-projects

**Comment by soundar24** [comment]
Package was successfully added with npm already:
https://www.npmjs.com/package/round-slider
