### ISSUE TITLE
Set Step

### ISSUE THREAD

**Issue by VinceLearn** [soundar24/roundSlider#56]
I want to set different step length in different range, like,35\~48,step is 1, 48\~50, step is 2, 50\~60,step is 5.

**Comment by soundar24** [comment]
I am little bit strange with your requirement, since here the step values are differ within a small range. So i just made the below workaround for this, check the below demo and let me know your comments:

http://jsfiddle.net/soundar24/LpuLe9tr/737/

**Comment by VinceLearn** [comment]
Yes,it's my need.Thanks : ).
