### ISSUE TITLE
Decimal Values

### ISSUE THREAD

**Issue by SgtWiggidy** [soundar24/roundSlider#57]
I am using this fantastic plugin but I had a question. Is it possible to support decimal values. I am using the range option (-5 to 5) and wanted to use a value of 4.2 or similiar. Is this possible?

**Comment by soundar24** [comment]
I hope you expect the step functionality. Check the below demo and update me your comments..
**http://jsfiddle.net/soundar24/LpuLe9tr/774/**

**Comment by roysG** [comment]
WOW, you save me time :)
