### ISSUE TITLE
Zig Zag?

### ISSUE THREAD

**Issue by vilbht** [soundar24/roundSlider#59]
Hi there

Any tips to create a Zig Zag slider option?

Thanks

**Comment by soundar24** [comment]
Hi @vilav,

Zig Zag slider means what you mean, What functionality you want to achieve ? Can you describe your requirement, since i can't identify what the zig-zag functionality will do.

**Comment by vilbht** [comment]
HI @soundar24, sorry about the unclear msg. I meant something like the attached. That the slider handle could move along different axisas you dragged it along (different positions denoted in attachment by position 1 > 2 > 3 > 4) So instead of a straight line, it's a non-linear,  line

<img width="758" alt="screen shot 2017-01-20 at 3 55 01 pm" src="https://cloud.githubusercontent.com/assets/849098/22140680/e3c6266c-df28-11e6-924d-3fe2f624d6af.png">

**Comment by soundar24** [comment]
Actually the slider works only in a circular way, so you can't move the handle in different direction. Also it seems the requirement doesn't relate to roundSlider concept.

I hope you need something like a path slider, you can try the below one:
**http://mottie.github.io/Pathslider/index.html**

**Comment by vilbht** [comment]
@soundar24 that's awesome! thanks so  much!
