### ISSUE TITLE
Disabled / readonly handle

### ISSUE THREAD

**Issue by Hydro8** [soundar24/roundSlider#68]
Hi
I'm using your plugin it's a great work !

I'm trying to use it in my home automation website.
Basically I've got a round slider for my heat, one handle to represent the current heat level and one handle to represent the desire heat level.

I saw your fiddle : [http://jsfiddle.net/soundar24/utqgufx0/6/](http://jsfiddle.net/soundar24/utqgufx0/6/)

It's ok but I want to have a handle disabled or readonly, just to show current level whithout sliding it.
 
Do you think it's possible or do you think I can achieve this in another way ?

Thank

**Comment by soundar24** [comment]
I have updated the demo based on your requirement by some sample level customization. Check the below demo and let me know your comments:

## http://jsfiddle.net/soundar24/utqgufx0/456/

**Comment by Hydro8** [comment]
Great ! It's near !

Is it possible to have touch / click enable to move the first handle ?

When I use obj.setValue, or if I move with mouse, I can't have the two handle with the same value.

If I choose 24° for my heat, the second handle will be 24° too.

Thank for your help.

**Comment by Hydro8** [comment]
Sorry I don't close this issue yet :/

**Comment by Hydro8** [comment]
Do you have an idea why it doesn't seems to support click / touch ?

**Comment by soundar24** [comment]
I have updated the demo based on your requirement, check this and let me know your comments:

## http://jsfiddle.net/soundar24/utqgufx0/462/

**Comment by Hydro8** [comment]
It work great !! Thank a lot !

Just to annoying you, is it possible to write a text / icon in the center of the roundslider ?

**Comment by Hydro8** [comment]
Sorry I find a way to do it :)

Thank again. !

**Comment by soundar24** [comment]
You are always welcome ... :)
