### ISSUE TITLE
Stop command with value

### ISSUE THREAD

**Issue by Hydro8** [soundar24/roundSlider#7]
Hi

I try to use stop command to fire a function that use slider value but slider value doesn't seem to be passed to the function.

Do you have a way to pass value to stop function ?

**Comment by soundar24** [comment]
Hi,

You can use the "stop" event like below:

```
       $("#slider").roundSlider({
            value: 45,

            stop: function (e) {
                //here this.options.value gives the slider value
                console.log(this.options.value);

                //here e.handle gives the current dragged handle details
                console.log(e);
            }
        });
```

For range slider case, `e.handle.value` gives the current handle value like 40. But `this.options.value` gives the range value "20,40". 

And `e.handle.index` gives the handle index, `e.handle.element` gives the current handle object.

For details check the console for arguments details.

Some demos:
[jsBin](http://jsbin.com/ceruqecexu/edit?html,output)
[jsFiddle](http://jsfiddle.net/soundar24/LpuLe9tr/177/)

Thanks...

**Comment by soundar24** [comment]
Since the comments was updated for the question, so closed this report. Please let me know if any further details needed.
