### ISSUE TITLE
Stops scrolling when mouse exits the containing element, in Angular 2

### ISSUE THREAD

**Issue by Dakien** [soundar24/roundSlider#72]
I'm using roundslider in my typescript based angular 2 project, and it seems to have a problem with the click/drag events, whenever the cursor is no longer within the 180px x 180px square div that holds the slider it stops scrolling.

Bellow is the declaration of the roundSlider, where OnSliderUpdate is just a function to record the value of the slider.
`this.slider = (jQuery('#mood-slider') as any).roundSlider({
			radius: 90,
			width: 18,
			value: 0,
			handleSize: '+12',
			step: 1,
			min: 0,
			max: 99,
			handleShape: 'dot',
			mouseScrollAction: true,
			editableTooltip: false,
			showTooltip: false,
			startAngle: 90,
			drag: (e) => {
				this.onSliderUpdate(e.value);
			},
			change: (e) => {
				this.onSliderUpdate(e.value);
			}
		});`

**Comment by soundar24** [comment]
Is there any possibility to send the demo link for your application, to see the issue in live. So that i can easily identify the issue.

**Comment by soundar24** [comment]
@Dakien, I am closing this since I didn't get any update from you still. If you need any further assistance then you can re-open this or create a new bug report. Thanks...
