### ISSUE TITLE
Is it possible to decide the values of the round slider?

### ISSUE THREAD

**Issue by maryam-abdullah** [soundar24/roundSlider#74]
I was wondering if it's possible to decide the values in the round slider.
It doesn't have to be the same difference between values. 
For example 2, 5, 10.
Or even 5, 10, 20, 30.

Thanks in advance.

**Comment by soundar24** [comment]
Are you expect the non-linear increment slider. Check the below report and let me know whether this is your requirement or not:
https://github.com/soundar24/roundSlider/issues/22

Check the @wobi03 comments from there, I hope that fulfills your requirement. Like that you can write your own logic.

**Comment by maryam-abdullah** [comment]
Yes, that's what I meant.

I actually applied a slight change for @wobi03 comments.

```
$.fn["roundSlider"].prototype._tooltipValue = function(value, index) {
    var val = this._raise("tooltipFormat", { value: value, "handle": this._handleArgs(index) });
    var ct = this.options.customTicks; 
    if(typeof(ct) !== 'undefined' && ct.length > 0){
      val = this._raise("tooltipFormat", { value: ct[value], "handle": this._handleArgs(index) });
    }
    return (val != null && typeof val !== "boolean") ? val : ct[value];
}

```
Since it was returning the index value of the array and not the value at that position.

Thanks a lot.

**Comment by soundar24** [comment]
👍
