### ISSUE TITLE
Is it possible to define a round slider, and later on change its customized values according to an event?

### ISSUE THREAD

**Issue by maryam-abdullah** [soundar24/roundSlider#75]
Hello,

I was wondering if it's possible to modify some attributes of a round slider upon events after they've been defined,
or do I have to define a new slider each time this event occurs?

Thanks in advance.

**Comment by soundar24** [comment]
I can't get your exact problem, is this solved now?

I hope you may need to get or set the properties value dynamically, refer the below document once:
http://roundsliderui.com/document.html#how-to-use-options

**Comment by maryam-abdullah** [comment]
Yes, that was my point.
But I was trying to set the value of my custom options and not the predefined ones.
I closed the issue cause I found the solution.
`$(".planrange_slider").data("roundSlider").options.customTicks`

Thank you.
