### ISSUE TITLE
Transparancy from 0-10%

### ISSUE THREAD

**Issue by Time4u2run** [soundar24/roundSlider#78]
I would like to create a roundSlider starting with "10%" at startAngle 126 reaching until "100%" at endAngle 90. So basically I just want the path-color between 0% to 10% to be transparent. How can I reach this?

**Comment by soundar24** [comment]
@Time4u2run I can't get your exact requirement, based on my understanding I made the below demo:
http://jsfiddle.net/soundar24/yf7fqrs4/1/

If this is not your requirement then update me the additional details (with any screenshot).

**Comment by Time4u2run** [comment]
Hello Soundar24,
This is exactly the shape that I meant. Now I want to hide the space between 0% to 10%, so it is completely white and there are no stripes from the circle.

Thank you in advance!

**Comment by soundar24** [comment]
Here I have updated 2 possible solutions for your requirement, check and let me know if you have any concerns on these:
1) http://jsfiddle.net/soundar24/yf7fqrs4/4/

2) https://jsfiddle.net/soundar24/1usqdvc9/40/

**Comment by soundar24** [comment]
@Time4u2run This might be after a very long back, but a new update for you.

roundSlider was release with SVG mode support, so your mentioned requirement can be achieved in a simplified way.
### https://jsfiddle.net/soundar24/r5jcb1q4/2/

Check the above demo and you can let me know if you have any questions.
