### ISSUE TITLE
Drag callback not working for Ionic 4

### ISSUE THREAD

**Issue by warjohn123** [soundar24/roundSlider#85]
First and foremost, I'd like to say thank you for the awesome plugin. Now, I was able to successfully import this plugin to my ionic application. I was trying to include 'drag' callback so that a function emits every time a user drags the circle. But what happens in my case is that the drag callback isn't fired during the drag event. It only fire after the user drags and clicks the screen. It might be that this feature is not supported in the mobile part?

**Comment by soundar24** [comment]
I have modified the sample to support function handlers, please check the below demo:

### https://jsfiddle.net/soundar24/hv3sucrx/

Check and let me know your comments.

**Comment by warjohn123** [comment]
I'm currently using Ionic 4. Is there a sample for Ionic 4?

**Comment by soundar24** [comment]
Sorry, I am not much aware of ionic latest versions.. I hope this is the generic solution only, so it will work in any version or environment. Just try in your application and confirm me whether you have faced any issues with this.
