### ISSUE TITLE
Array for step Option

### ISSUE THREAD

**Issue by alphaelf** [soundar24/roundSlider#86]
can you improve step option to get an array of allowed values? 
user can select only one of this value in min-max range

e.g: we have a slider for choosing speed of internet service form 1 to 16 mb/s and available speed is `[1,2,3,4,8,16] `  so i think is better to do this by step option, if it gets number it's normal step and if gets array it's specificated points

**Comment by soundar24** [comment]
@alphaelf  Actually similar behavior was already considered in the non-linear step increment, but your current mentioned requirement is simple linear type only which can be achieved in the application level itself. Please check the below demo:

### https://jsfiddle.net/soundar24/s5gpugjn/880/

If you need the same for your application then you can use this solution, if you need any additional functionality then you can let me know.

**Comment by alphaelf** [comment]
Ok, your example work but `getValue` need to modify,
i use this code for my application:
```javascript
// packs = { '1': {...},'2': {...},'3': {...},'8': {...} }
let keys = Object.keys(packs),
        i = keys.indexOf(e.preValue.toString())
    if(!keys.includes(e.value.toString()))
    {
        if(e.value > e.preValue) i++; else i--;
        $("#speed").roundSlider("setValue", keys[i])
    }
```
this code run on `change` event of speed slider
thanks to replay

**Comment by soundar24** [comment]
Oh fine, but I hope you can simply achieve this like below:
https://jsfiddle.net/soundar24/s5gpugjn/888/

**Comment by alphaelf** [comment]
thank's a lot, i close issue
