### ISSUE TITLE
LineCap is not listed in documentation

### ISSUE THREAD

**Issue by itsmichaeldiego** [soundar24/roundSlider#87]
Hello @soundar24, first of all, thank you so much for your library, it has been super useful to me.

I wanted to let you know that the property `lineCap` is listed in the [options in the Readme.md](https://github.com/soundar24/roundSlider#options) but it is not listed in the [documentation in your website](http://roundsliderui.com/document.html#options)

Regards

**Comment by soundar24** [comment]
Thanks for the update @itsmichaeldiego .. at that time I was busy with another work.. now i have updated the [documentation](http://roundsliderui.com/document.html) as well as the [playground](http://roundsliderui.com/playground.html)... 👍

**Comment by itsmichaeldiego** [comment]
Thanks @soundar24, your library worked pretty well and saved me a lot of time, although I needed it for React so I have to adapt, have you thought about creating the same library with React?

**Comment by itsmichaeldiego** [comment]
@soundar24 BTW just checked the documentation and the playgroud. It is looking great, I will move ahead and close the issue, thanks again! 🎉

**Comment by soundar24** [comment]
You are welcome.. I hope you can use any jQuery plugin in react, so you can try in that way.. if you are faced any issue then you can let me know.. Thanks :)
