### ISSUE TITLE
Invert range selection for roundSlider (ex: 10 - 5)

### ISSUE THREAD

**Issue by vuau** [soundar24/roundSlider#9]
Let's say we have a circle from 0 to 11 and sliderType is "range".
Normally I will drag 2 handler to select a range of 2 to 9 for example. Now I need to select a range from 10 to 1 to fulfil the circle. Is it possible to do that?

**Comment by rolandschuetz** [comment]
A simple solution would be to just change the handle color to e.g. white and the background-color to something strong like red. 
Then visually it would appear that exactly the other part is highlighted. 

[Playground configuration](https://www.dropbox.com/s/y81ponwn3nwhj1u/Bildschirmfoto%202016-01-05%20um%2001.17.03.png?dl=0)

So the only thing you would need to do is to adopt the tooltip rendering.

**Comment by soundar24** [comment]
This is also cool and great work, but for this case you need to do more workaround in the sample level. 

But don't worry about this, since i already implemented this in source. So it will be included in the next version.

**Comment by vuau** [comment]
awesome. thank you both.

**Comment by soundar24** [comment]
@phamvuau , with the 1.2 version of roundSlider I just updated some codes based on this requirement. Please check the below demo and update me your comments:
**http://jsfiddle.net/soundar24/cssbtg32/1/**

Please let me know if anything missed or need to improve.. In the next version i will provide the complete functionality through any property.
