### ISSUE TITLE
Set a value out of range

### ISSUE THREAD

**Issue by mnajafzadeh** [soundar24/roundSlider#91]
Hi,

Thank you for this great library.

Please let me know is there a way to input a value out of the range? for example, if the range limit is between 1-100 (by default) is there a way to input value like 300 in the slider? If there is not such a feature of how we can customize it to doing it?

This is important for us because one of our sliders value calculated based on other ones and we don't know range limit for result slider so we want to change result slider value regularly based on other sliders value.

We tried to set a value of range for result value but it doesn't allow to do it.

If there is a way to change the min-max range of slider regularly it can help us, for example, if the user changes the value to 1000 we can first change the max to 10000 and I think it can works. 

Please let us know your idea.

Thanks.

**Comment by soundar24** [comment]
Actually 0 - 100 range is the default value, you can change your desirable value through "[min](https://roundsliderui.com/document.html#min)" and "[max](https://roundsliderui.com/document.html#max)" properties, also you can use the "[step](https://roundsliderui.com/document.html#step)" property to manage the handle movement or value round off.

Also, you can change these values dynamically based on your usecase. Check the below demo where I have handled the values dynamically, like that you can define your own logic:
https://jsfiddle.net/soundar24/x10rbfqp/77/

Check the below documentation for the list of options available, by using these you can do any customization:
https://roundsliderui.com/document.html#options

Also see the ways to use these options in the application:
https://roundsliderui.com/document.html#how-to-use-options

Hope these helps, still any doubt you can let me know.

**Comment by mnajafzadeh** [comment]
Hi @soundar24,

Thank you for your response and your explanations.

To do the same customization on a slider inside input we write below code to edit min, max when possible but it does not work, please let us know is there any way to edit min, max when slider inside input value changes?

```javascript
const limitValue = jQuery.fn.roundSlider.prototype._limitValue
jQuery.fn.roundSlider.prototype._limitValue = function(val) {
  let min = this.options.min,
      max = this.options.max
  if (val >= max || val <= min) {
    min = 0,
    max = 100;
    if (0 < val) {
      max = ('' + val).split('.')[0].length;
      max = 0 == max ? 1 : Math.pow(10, max);
    } else if (0 > val) {
      max = 0;
      min = ('' + val).split('.')[0].length - 1;
      min = 0 >= min ? -1 : Math.pow(10, min) * -1;
    }

    this._set('min', min)
    this._set('max', max)
  }

  return limitValue.call(this, val)
}
```

Thanks.

**Comment by soundar24** [comment]
To customize the input value when change through the tooltip, you can overwrite the "_focusOut" function. Check the below demo:
https://jsfiddle.net/soundar24/x10rbfqp/78/

Check this and let me know whether it resolves your problem. If still facing any issues then let me know the details, also update your use-case scenario so that if any better option available then I can suggest.

**Comment by mnajafzadeh** [comment]
Hi @soundar24,

Thank you for your great help, it worked.
