### ISSUE TITLE
Is there any way to show Label around Slider..?

### ISSUE THREAD

**Issue by GRASPARK** [soundar24/roundSlider#94]
I need show Label around Round Slider as per below screen shot:

![Round-Slider-with-Label](https://user-images.githubusercontent.com/3957311/61056493-124dd200-a411-11e9-8a4a-9694962a1145.png)

I have try some of the below solution:
- http://jsfiddle.net/soundar24/LpuLe9tr/290/
- http://jsfiddle.net/soundar24/LpuLe9tr/182/
- http://jsfiddle.net/soundar24/LpuLe9tr/819/

But it didn't shows according to that with smooth drag effect to Round Slider.

Is it possible..?

**Comment by soundar24** [comment]
I hope from the second demo you can get the logic and you can understand easily. I just created another demo based on your requirement, by placing the number generation script and css you can simply achieve this.

## https://jsfiddle.net/soundar24/x10rbfqp/90/

Check this and let me know if you have any doubts.\

**Comment by GRASPARK** [comment]
Thanks @soundar24, it works for me.
