### ISSUE TITLE
restart the value when click on button

### ISSUE THREAD

**Issue by setarbgram** [soundar24/roundSlider#95]
Hi everyone ... 

I use the jquery-3.3.1 in my project .  roundslider is worked correctly out of document.ready, but when I use into document.ready it shows this error "$(...).roundSlider is not a function"
even I want to change the value in javascript it shows that error, too. 
although i change jquery to  jquery-1.11 the error is remained. 
how can I solve this problem?

**Comment by soundar24** [comment]
I hope the problem with your application only, before call the roundSlider just check whether the corresponding element is available or not.

I have created 2 sample with both the jquery versions 1.11.3 and 3.3.1, where there is no problem. Check the below demos:
https://jsbin.com/rivohidine/edit?html,js,console,output
https://jsbin.com/cusuxipuve/edit?html,js,console,output

Still if you faced any issue then let me know some more details to reproduce this issue, or update me the jsbin sample with the issue reproduced.
